import type { ComponentCategory, ComponentRegistryEntry } from "../types";

/**
 * Complete registry of all 55 component exports from @rhinolabs/ui.
 *
 * This is DATA ONLY — no React, no JSX, no imports from the UI library.
 * Each consumer app reads this registry and renders components in its own
 * test files using its own React version and @testing-library/react.
 */
export const componentRegistry: ComponentRegistryEntry[] = [
  // ─── Display ───────────────────────────────────────────────────────────────

  {
    name: "Alert",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Test alert", variant: "default" },
    category: "display",
  },
  {
    name: "Badge",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "New Badge" },
    category: "display",
  },
  {
    name: "Card",
    hasSubComponents: true,
    subComponentNames: ["Header", "Title", "Description", "Content", "Footer"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Card content" },
    category: "display",
  },
  {
    name: "Empty",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Nothing here" },
    category: "display",
  },
  {
    name: "Item",
    hasSubComponents: true,
    subComponentNames: ["Media", "Content", "Actions", "Group", "Separator", "Title", "Description", "Header", "Footer"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Item content" },
    category: "display",
  },
  {
    name: "Kbd",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Ctrl+C" },
    category: "display",
  },
  {
    name: "Skeleton",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "display",
  },
  {
    name: "Spinner",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "display",
  },
  {
    name: "Typography",
    hasSubComponents: true,
    subComponentNames: [
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
      "P",
      "Blockquote",
      "List",
      "ListItem",
      "InlineCode",
      "Lead",
      "Large",
      "Small",
      "Muted",
    ],
    requiresProvider: true, // Not a renderable component — namespace object only
    requiresThemeProvider: false,
    minimalProps: {},
    category: "display",
  },
  {
    name: "Avatar",
    hasSubComponents: true,
    subComponentNames: ["Image", "Fallback"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "display",
  },
  {
    name: "Progress",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { value: 50 },
    category: "display",
  },
  {
    name: "Table",
    hasSubComponents: true,
    subComponentNames: [
      "Header",
      "Body",
      "Footer",
      "Row",
      "Head",
      "Cell",
      "Caption",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "display",
  },

  // ─── Layout ────────────────────────────────────────────────────────────────

  {
    name: "AspectRatio",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { ratio: 16 / 9 },
    category: "layout",
  },
  {
    name: "ButtonGroup",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "layout",
  },
  {
    name: "ScrollArea",
    hasSubComponents: true,
    subComponentNames: ["Bar"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { style: { height: 100 } },
    category: "layout",
  },
  {
    name: "Separator",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "layout",
  },

  // ─── Form (simple) ────────────────────────────────────────────────────────

  {
    name: "Input",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { placeholder: "test" },
    category: "form",
  },
  {
    name: "Textarea",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { placeholder: "test" },
    category: "form",
  },
  {
    name: "Label",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Test label" },
    category: "form",
  },
  {
    name: "NativeSelect",
    hasSubComponents: true,
    subComponentNames: ["Option", "OptGroup"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "InputGroup",
    hasSubComponents: true,
    subComponentNames: ["Input", "Text"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "Field",
    hasSubComponents: true,
    subComponentNames: [
      "Label",
      "Description",
      "Error",
      "Group",
      "Legend",
      "Separator",
      "Set",
      "Content",
      "Title",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "Checkbox",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "Switch",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "Slider",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { defaultValue: [50] },
    category: "form",
  },
  {
    name: "RadioGroup",
    hasSubComponents: true,
    subComponentNames: ["Item"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { defaultValue: "a" },
    category: "form",
  },
  {
    name: "Select",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Value",
      "Content",
      "Group",
      "Item",
      "Label",
      "Separator",
      "ScrollUpButton",
      "ScrollDownButton",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },
  {
    name: "MultipleSelect",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {
      options: [
        { label: "Apple", value: "apple" },
        { label: "Banana", value: "banana" },
        { label: "Cherry", value: "cherry" },
        { label: "Date", value: "date" },
      ],
      value: ["apple"],
      onChange: "NOOP_FN",
    },
    category: "form",
  },
  {
    name: "InputOTP",
    hasSubComponents: true,
    subComponentNames: ["Group", "Slot", "Separator"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { maxLength: 4 },
    category: "form",
  },
  {
    // KNOWN BUG (PR #84): Calendar is broken with React 18. The component code
    // was rewritten for react-day-picker v9 API, but v9 requires React 19.
    // Do NOT attempt to fix here — the component itself needs to be updated.
    name: "Calendar",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },

  // ─── Interactive ───────────────────────────────────────────────────────────

  {
    name: "Button",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "Click me", onClick: "ALERT_FN" },
    category: "interactive",
  },
  {
    name: "Toggle",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { children: "T" },
    category: "interactive",
  },
  {
    name: "ToggleGroup",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { type: "single" },
    category: "interactive",
  },
  {
    name: "Accordion",
    hasSubComponents: true,
    subComponentNames: ["Item", "Trigger", "Content"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { type: "single", collapsible: true },
    category: "interactive",
  },
  {
    name: "Collapsible",
    hasSubComponents: true,
    subComponentNames: ["Trigger", "Content"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "interactive",
  },
  {
    name: "Tabs",
    hasSubComponents: true,
    subComponentNames: ["List", "Trigger", "Content"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { defaultValue: "a" },
    category: "interactive",
  },
  {
    name: "Carousel",
    hasSubComponents: true,
    subComponentNames: ["Content", "Item", "Previous", "Next"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "interactive",
  },
  {
    name: "ResizablePanelGroup",
    hasSubComponents: true,
    subComponentNames: ["Panel", "Handle"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: { direction: "horizontal" },
    category: "interactive",
  },

  // ─── Overlay ───────────────────────────────────────────────────────────────

  {
    name: "Dialog",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Portal",
      "Close",
      "Overlay",
      "Content",
      "Header",
      "Footer",
      "Title",
      "Description",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "AlertDialog",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Content",
      "Header",
      "Footer",
      "Title",
      "Description",
      "Action",
      "Cancel",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "Sheet",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Close",
      "Content",
      "Header",
      "Footer",
      "Title",
      "Description",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "Drawer",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Portal",
      "Close",
      "Overlay",
      "Content",
      "Header",
      "Footer",
      "Title",
      "Description",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "Popover",
    hasSubComponents: true,
    subComponentNames: ["Trigger", "Content", "Anchor"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "HoverCard",
    hasSubComponents: true,
    subComponentNames: ["Trigger", "Content"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "Tooltip",
    hasSubComponents: true,
    subComponentNames: ["Trigger", "Content", "Provider"],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "DropdownMenu",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Content",
      "Item",
      "CheckboxItem",
      "RadioItem",
      "Label",
      "Separator",
      "Shortcut",
      "Group",
      "Sub",
      "SubTrigger",
      "SubContent",
      "RadioGroup",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },
  {
    name: "ContextMenu",
    hasSubComponents: true,
    subComponentNames: [
      "Trigger",
      "Content",
      "Item",
      "CheckboxItem",
      "RadioItem",
      "Label",
      "Separator",
      "Shortcut",
      "Group",
      "Sub",
      "SubTrigger",
      "SubContent",
      "RadioGroup",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "overlay",
  },

  // ─── Navigation ────────────────────────────────────────────────────────────

  {
    name: "Breadcrumb",
    hasSubComponents: true,
    subComponentNames: [
      "List",
      "Item",
      "Link",
      "Page",
      "Separator",
      "Ellipsis",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },
  {
    name: "Pagination",
    hasSubComponents: true,
    subComponentNames: [
      "Content",
      "Item",
      "Link",
      "Previous",
      "Next",
      "Ellipsis",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },
  {
    name: "Menubar",
    hasSubComponents: true,
    subComponentNames: [
      "Menu",
      "Trigger",
      "Content",
      "Item",
      "Separator",
      "Label",
      "Group",
      "Sub",
      "SubContent",
      "SubTrigger",
      "CheckboxItem",
      "RadioGroup",
      "RadioItem",
      "Shortcut",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },
  {
    name: "NavigationMenu",
    hasSubComponents: true,
    subComponentNames: [
      "List",
      "Item",
      "Trigger",
      "Content",
      "Link",
      "Indicator",
      "Viewport",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },
  {
    name: "Command",
    hasSubComponents: true,
    subComponentNames: [
      "Dialog",
      "Input",
      "List",
      "Empty",
      "Group",
      "Item",
      "Shortcut",
      "Separator",
    ],
    requiresProvider: false,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },
  {
    name: "Sidebar",
    hasSubComponents: true,
    subComponentNames: [
      "Provider",
      "Trigger",
      "Rail",
      "Inset",
      "Input",
      "Header",
      "Footer",
      "Separator",
      "Content",
      "Group",
      "GroupLabel",
      "GroupAction",
      "GroupContent",
      "Menu",
      "MenuItem",
      "MenuButton",
      "MenuAction",
      "MenuSub",
      "MenuSubButton",
      "MenuSubItem",
      "MenuBadge",
      "MenuSkeleton",
    ],
    requiresProvider: true,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "navigation",
  },

  // ─── Form (complex — requires react-hook-form context) ────────────────────

  {
    name: "Form",
    hasSubComponents: true,
    subComponentNames: [
      "Root",
      "Item",
      "Label",
      "Control",
      "Description",
      "Message",
      "Field",
    ],
    requiresProvider: true,
    requiresThemeProvider: false,
    minimalProps: {},
    category: "form",
  },

  // ─── Feedback (requires next-themes ThemeProvider) ─────────────────────────

  {
    name: "Toaster",
    hasSubComponents: false,
    subComponentNames: [],
    requiresProvider: false,
    requiresThemeProvider: true,
    minimalProps: {},
    category: "feedback",
  },
];
